### ISSUE TITLE
googletest needs update

### ISSUE THREAD

**Issue by vagetablechicken** [jingchen2222/hybridsql-asserts#11]
We'll use `GTEST_ALLOW_UNINSTANTIATED_PARAMETERIZED_TEST` in hybridse on mac. But googletest-1.10.0 doesn't have this macro.
The gtest lib in released mac thirdparty, is not 1.10.0. Let's update it to v1.11.0.

**Comment by aceforeverd** [comment]
wow~, that's why I compile failed on Linux if `GTEST_ALLOW_UNINSTANTIATED_PARAMETERIZED_TEST` is added.
This marco might added to linux version as well to avoid UT number change

**Comment by vagetablechicken** [comment]
> wow~, that's why I compile failed on Linux if `GTEST_ALLOW_UNINSTANTIATED_PARAMETERIZED_TEST` is added.
> This marco might added to linux version as well to avoid UT number change

It will failed on Mac too. So if we update gtest to 1.11, we can remove the `ifdef __APPLE__` macro?

https://github.com/4paradigm/HybridSE/blob/5ca13ff068eaffaa60419036154daa4b749906bd/src/testing/engine_test_base.cc#L482

**Comment by vagetablechicken** [comment]
`syscall` is deprecated since Mac 10.12. Needs fix too.

**Comment by vagetablechicken** [comment]
disable some libs shared building
